// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUdFCWoLNXteK6u8oiRSXCxxd3JFwDedA',
    appId: '1:68968849891:web:4005cd5a03c4c95f2500d6',
    messagingSenderId: '68968849891',
    projectId: 'todo-e21cb',
    authDomain: 'todo-e21cb.firebaseapp.com',
    storageBucket: 'todo-e21cb.firebasestorage.app',
    measurementId: 'G-8GFD9L2XXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALCuYayePQD2DJD30hW9tTZvZlJQdlPo4',
    appId: '1:68968849891:android:e10dce48b5c226892500d6',
    messagingSenderId: '68968849891',
    projectId: 'todo-e21cb',
    storageBucket: 'todo-e21cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyVN3fXpkW7k31nLi0Pe-lkBImC352u9o',
    appId: '1:68968849891:ios:bc9b248e4463eb8a2500d6',
    messagingSenderId: '68968849891',
    projectId: 'todo-e21cb',
    storageBucket: 'todo-e21cb.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyVN3fXpkW7k31nLi0Pe-lkBImC352u9o',
    appId: '1:68968849891:ios:bc9b248e4463eb8a2500d6',
    messagingSenderId: '68968849891',
    projectId: 'todo-e21cb',
    storageBucket: 'todo-e21cb.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUdFCWoLNXteK6u8oiRSXCxxd3JFwDedA',
    appId: '1:68968849891:web:9c5f1e52c4dc94502500d6',
    messagingSenderId: '68968849891',
    projectId: 'todo-e21cb',
    authDomain: 'todo-e21cb.firebaseapp.com',
    storageBucket: 'todo-e21cb.firebasestorage.app',
    measurementId: 'G-KYNENT7WFW',
  );
}
